import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import dynamic from 'next/dynamic'
import { cookies } from "next/headers";
import Navbar from "../components/Navbar";
// const Navbar = dynamic(() => import('../components/Navbar'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesList = cookies()
  const token = cookiesList.get('token')
  return (

    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="bg-slate-800 h-screen text-white ">
            <Navbar token={token} />
            {children}
        </main>
      </body>
    </html>
  );
}
